### ISSUE TITLE
srs.sh: 文件里的命令没写适配？只能用Mac系统么

### ISSUE THREAD

**Issue by dong-lufei** [galaxy-s10/billd-live-server#1]
项目怎么跑应该描述一下呀；在哪里配置等等。你那配置文件都把MySQL数据库和redis数据库的默认端口都改了。我改后报错：
 ```
SUCCESS  加载所有route成功~
 INFO  当前不是beta环境，初始化websocket
 SUCCESS  项目启动成功！
 WARN  当前监听的端口: 4300
 WARN  当前的项目名称: billd-live-server
 WARN  当前的项目环境: development
 INFO  2023/5/3 22:03:17，子进程退出了，sh E:\test\billd-live-server\srs.sh
 INFO  2023/5/3 22:03:17，有打印
Error: Command failed: sh E:\test\billd-live-server\srs.sh
E:\test\billd-live-server\srs.sh: line 16: ifconfig: command not found
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs/stop": open //./pipe/docker_engine: The system cannot find the file specified.
error during connect: This error may indicate that the docker daemon is not running.: Delete "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs": open //./pipe/docker_engine: The system cannot find the file specified.
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'sh E:\\test\\billd-live-server\\srs.sh'
} 停掉旧的容器billd-live-server-srs:
删掉旧的容器billd-live-server-srs:
启动新的容器billd-live-server-srs:
```

**Comment by galaxy-s10** [comment]
你微信多少，我加你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 董路飞 ***@***.***&gt;
发送时间: 2023年5月3日 22:10
收件人: galaxy-s10/billd-live-server ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [galaxy-s10/billd-live-server] srs.sh: 文件里的命令没写适配？只能用Mac系统么 (Issue #1)





 
项目怎么跑应该描述一下呀；在哪里配置等等。你那配置文件都把MySQL数据库和redis数据库的默认端口都改了。我改后报错：
 SUCCESS  加载所有route成功~ INFO  当前不是beta环境，初始化websocket SUCCESS  项目启动成功！ WARN  当前监听的端口: 4300 WARN  当前的项目名称: billd-live-server WARN  当前的项目环境: development INFO  2023/5/3 22:03:17，子进程退出了，sh E:\test\billd-live-server\srs.sh INFO  2023/5/3 22:03:17，有打印 Error: Command failed: sh E:\test\billd-live-server\srs.sh E:\test\billd-live-server\srs.sh: line 16: ifconfig: command not found error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs/stop": open //./pipe/docker_engine: The system cannot find the file specified. error during connect: This error may indicate that the docker daemon is not running.: Delete "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs": open //./pipe/docker_engine: The system cannot find the file specified. docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified. See 'docker run --help'.    at ChildProcess.exithandler (node:child_process:419:12)    at ChildProcess.emit (node:events:513:28)    at ChildProcess.emit (node:domain:489:12)    at maybeClose (node:internal/child_process:1091:16)    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {  code: 127,  killed: false,  signal: null,  cmd: 'sh E:\\test\\billd-live-server\\srs.sh' } 停掉旧的容器billd-live-server-srs: 删掉旧的容器billd-live-server-srs: 启动新的容器billd-live-server-srs:

**Comment by galaxy-s10** [comment]
> 项目怎么跑应该描述一下呀；在哪里配置等等。你那配置文件都把MySQL数据库和redis数据库的默认端口都改了。我改后报错：
> 
> ```
> SUCCESS  加载所有route成功~
> INFO  当前不是beta环境，初始化websocket
> SUCCESS  项目启动成功！
> WARN  当前监听的端口: 4300
> WARN  当前的项目名称: billd-live-server
> WARN  当前的项目环境: development
> INFO  2023/5/3 22:03:17，子进程退出了，sh E:\test\billd-live-server\srs.sh
> INFO  2023/5/3 22:03:17，有打印
> Error: Command failed: sh E:\test\billd-live-server\srs.sh
> E:\test\billd-live-server\srs.sh: line 16: ifconfig: command not found
> error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs/stop": open //./pipe/docker_engine: The system cannot find the file specified.
> error during connect: This error may indicate that the docker daemon is not running.: Delete "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/billd-live-server-srs": open //./pipe/docker_engine: The system cannot find the file specified.
> docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
> See 'docker run --help'.
> 
>    at ChildProcess.exithandler (node:child_process:419:12)
>    at ChildProcess.emit (node:events:513:28)
>    at ChildProcess.emit (node:domain:489:12)
>    at maybeClose (node:internal/child_process:1091:16)
>    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
>  code: 127,
>  killed: false,
>  signal: null,
>  cmd: 'sh E:\\test\\billd-live-server\\srs.sh'
> } 停掉旧的容器billd-live-server-srs:
> 删掉旧的容器billd-live-server-srs:
> 启动新的容器billd-live-server-srs:
> ```

更新readme了，看看

**Comment by dong-lufei** [comment]
CANDIDATE=$(ifconfig en0 inet | grep 'inet ' | awk '{print $2}')
你这命令全球用户量最大的操作系统 windows 跑不了，windows 没有 ifconfig 命令 有ipconfig。windows 也可以跑docker和podman

**Comment by galaxy-s10** [comment]
> CANDIDATE=$(ifconfig en0 inet | grep 'inet ' | awk '{print $2}') 你这命令全球用户量最大的操作系统 windows 跑不了，windows 没有 ifconfig 命令 有ipconfig。windows 也可以跑docker和podman

苹果测试window需要模拟器，比较麻烦，后续再兼容，当然你也可以提pr~
