### ISSUE TITLE
希望能支持用obs推流

### ISSUE THREAD

**Issue by KKingwang** [galaxy-s10/billd-live-server#2]
希望能支持用obs推流，网页捕获屏幕还是有点单调

**Comment by galaxy-s10** [comment]
> 希望能支持用obs推流，网页捕获屏幕还是有点单调

目前开发就一个人，后面可能会考虑~

**Comment by galaxy-s10** [comment]
> 希望能支持用obs推流，网页捕获屏幕还是有点单调

今天开始支持obs、ffmpeg推流啦（beta），具体教程：[https://www.hsslive.cn/article/150](https://www.hsslive.cn/article/150)
