### ISSUE TITLE
初始化FFmpeg推流错误

### ISSUE THREAD

**Issue by YuChuanhui3** [galaxy-s10/billd-live-server#4]
[2024/9/4 14:19:42]  ERROR   初始化FFmpeg推流错误！
AxiosError [AggregateError]:
    at Function.AxiosError.from (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\core\AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\adapters\http.js:620:25)
    at RedirectableRequest.emit (node:events:531:35)
    at ClientRequest.eventHandlers.<computed> (C:\Project\billd-live\billd-live-server\node_modules\follow-redirects\index.js:39:24)
    at ClientRequest.emit (node:events:519:28)
    at Socket.socketErrorListener (node:_http_client:500:9)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at initFFmpeg (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:174:21) {
  code: 'ECONNREFUSED',
  errors: [
    Error: connect ECONNREFUSED ::1:1985
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 1985
    },
    Error: connect ECONNREFUSED 127.0.0.1:1985
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 1985
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 5000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.7',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://localhost:1985/api/v1/clients?start=0&count=9999',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/v1/clients?start=0&count=9999',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '1985',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/v1/clients',
      search: '?start=0&count=9999'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/v1/clients?start=0&count=9999 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:1985\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v1/clients?start=0&count=9999',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:1985/api/v1/clients?start=0&count=9999',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError:
      at internalConnectMultiple (node:net:1118:18)
      at afterConnectMultiple (node:net:1685:7) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}

**Comment by galaxy-s10** [comment]
未启动srs容器?

**Comment by galaxy-s10** [comment]
> [2024/9/4 14:19:42] ERROR 初始化FFmpeg推流错误！ AxiosError [AggregateError]: at Function.AxiosError.from (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\core\AxiosError.js:92:14) at RedirectableRequest.handleRequestError (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\adapters\http.js:620:25) at RedirectableRequest.emit (node:events:531:35) at ClientRequest.eventHandlers. (C:\Project\billd-live\billd-live-server\node_modules\follow-redirects\index.js:39:24) at ClientRequest.emit (node:events:519:28) at Socket.socketErrorListener (node:_http_client:500:9) at Socket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at processTicksAndRejections (node:internal/process/task_queues:82:21) at Axios.request (C:\Project\billd-live\billd-live-server\node_modules\axios\lib\core\Axios.js:45:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at initFFmpeg (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:174:21) { code: 'ECONNREFUSED', errors: [ Error: connect ECONNREFUSED ::1:1985 at createConnectionError (node:net:1648:14) at afterConnectMultiple (node:net:1678:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '::1', port: 1985 }, Error: connect ECONNREFUSED 127.0.0.1:1985 at createConnectionError (node:net:1648:14) at afterConnectMultiple (node:net:1678:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 1985 } ], config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [ 'xhr', 'http', 'fetch' ], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 5000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function], Blob: [class Blob] }, validateStatus: [Function: validateStatus], headers: Object [AxiosHeaders] { Accept: 'application/json, text/plain, _/_', 'Content-Type': undefined, 'User-Agent': 'axios/1.7.7', 'Accept-Encoding': 'gzip, compress, deflate, br' }, method: 'get', url: 'http://localhost:1985/api/v1/clients?start=0&count=9999', data: undefined }, request: <ref *1> Writable { _events: { close: undefined, error: [Function: handleRequestError], prefinish: undefined, finish: undefined, drain: undefined, response: [Function: handleResponse], socket: [Array], timeout: undefined, abort: undefined }, _writableState: WritableState { highWaterMark: 16384, length: 0, corked: 0, onwrite: [Function: bound onwrite], writelen: 0, bufferedIndex: 0, pendingcb: 0, [Symbol(kState)]: 17580812, [Symbol(kBufferedValue)]: null }, _maxListeners: undefined, _options: { maxRedirects: 21, maxBodyLength: Infinity, protocol: 'http:', path: '/api/v1/clients?start=0&count=9999', method: 'GET', headers: [Object: null prototype], agents: [Object], auth: undefined, family: undefined, beforeRedirect: [Function: dispatchBeforeRedirect], beforeRedirects: [Object], hostname: 'localhost', port: '1985', agent: undefined, nativeProtocols: [Object], pathname: '/api/v1/clients', search: '?start=0&count=9999' }, _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _eventsCount: 3, _onNativeResponse: [Function (anonymous)], _currentRequest: ClientRequest { _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, destroyed: false, _last: true, chunkedEncoding: false, shouldKeepAlive: true, maxRequestsOnConnectionReached: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, strictContentLength: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, _closed: false, socket: [Socket], _header: 'GET /api/v1/clients?start=0&count=9999 HTTP/1.1\r\n' + 'Accept: application/json, text/plain, _/_\r\n' + 'User-Agent: axios/1.7.7\r\n' + 'Accept-Encoding: gzip, compress, deflate, br\r\n' + 'Host: localhost:1985\r\n' + 'Connection: keep-alive\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: nop], agent: [Agent], socketPath: undefined, method: 'GET', maxHeaderSize: undefined, insecureHTTPParser: undefined, joinDuplicateHeaders: undefined, path: '/api/v1/clients?start=0&count=9999', _ended: false, res: null, aborted: false, timeoutCb: [Function: emitRequestTimeout], upgradeOrConnect: false, parser: null, maxHeadersCount: null, reusedSocket: false, host: 'localhost', protocol: 'http:', _redirectable: [Circular *1], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false, [Symbol(kBytesWritten)]: 0, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype], [Symbol(errored)]: null, [Symbol(kHighWaterMark)]: 16384, [Symbol(kRejectNonStandardBodyWrites)]: false, [Symbol(kUniqueHeaders)]: null }, _currentUrl: 'http://localhost:1985/api/v1/clients?start=0&count=9999', _timeout: null, [Symbol(shapeMode)]: true, [Symbol(kCapture)]: false }, cause: AggregateError: at internalConnectMultiple (node:net:1118:18) at afterConnectMultiple (node:net:1685:7) { code: 'ECONNREFUSED', [errors]: [ [Error], [Error] ] } }

未启动srs容器？

**Comment by YuChuanhui3** [comment]
0秒后开始初始化推流...[2024/11/19 09:58:08]  WARN    ffmpeg已安装，开始运行ffmpeg推流
[2024/11/19 09:58:08]  ERROR   初始化FFmpeg推流错误！
TypeError: Cannot read properties of undefined (reading 'PullDomain')
    at TencentcloudCssClass.getPullUrl (C:\Project\billd-live\billd-live-server\src\utils\tencentcloud-css.ts:207:49)
    at addLive (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:46:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at initFFmpeg (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:203:9)
大佬，启动ssr容器后又这样了[இ௰இ]

**Comment by galaxy-s10** [comment]
> 0秒后开始初始化推流...[2024/11/19 09:58:08] WARN ffmpeg已安装，开始运行ffmpeg推流 [2024/11/19 09:58:08] ERROR 初始化FFmpeg推流错误！ TypeError: Cannot read properties of undefined (reading 'PullDomain') at TencentcloudCssClass.getPullUrl (C:\Project\billd-live\billd-live-server\src\utils\tencentcloud-css.ts:207:49) at addLive (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:46:62) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async Promise.all (index 0) at initFFmpeg (C:\Project\billd-live\billd-live-server\src\init\initFFmpeg.ts:203:9) 大佬，启动ssr容器后又这样了[இ௰இ]

微信，shuisheng9905，拉你进群。
